version: '3.1'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/certs:/etc/nginx/certs
      - ./logs:/var/log/nginx/
      - ./www:/srv/www
    ports:
      - 8080:80
      - 8443:443